import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import '@arco-design/web-react/dist/css/arco.css';
import './globals.css';

import SmoothScrollLayout from '@/app/components/layouts/SmoothScrollLayout';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="myDemo" />
        <title>MyDemo</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 這邊放 ScrollSmoother 容器 */}
        <SmoothScrollLayout>
          {/* main 這層一定要包裹 children，不然滾動範圍會怪 */}
          <main className="w-full">{children}</main>
        </SmoothScrollLayout>
      </body>
    </html>
  );
}
