import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import '@arco-design/web-react/dist/css/arco.css';
import './globals.css';

import SmoothScrollLayout from '@/app/components/layouts/SmoothScrollLayout';
import Header from '@/app/components/ui/Header/Header';
import Footer from '@/app/components/ui/Footer/Footer';
 
import ArcoLayoutWrapper from '@/app/components/layouts/ArcoLayoutWrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="myDemo" />
        <title>MyDemo</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SmoothScrollLayout>
          <ArcoLayoutWrapper header={<Header />} footer={<Footer />}>
            {children}
          </ArcoLayoutWrapper>
        </SmoothScrollLayout>
      </body>
    </html>
  );
}
